spring:
  profiles:
    active: dev

  jackson:
    property-naming-strategy: SNAKE_CASE

  datasource:
    url: jdbc:postgresql://localhost:5432/mywallet
    username: mywallet_user
    password: mywallet_pass

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

  sql:
    init:
      mode: never

---
# DEV-профиль: добавляем путь к dev-миграциям и плейсхолдер для сидирования
spring:
  config:
    activate:
      on-profile: dev
  flyway:
    locations: classpath:db/migration,classpath:db/migration/dev
    placeholders:
      seed_user_id: 11111111-1111-1111-1111-111111111111

---
# PROD-профиль: только базовые миграции, можно скрыть SQL-лог
spring:
  config:
    activate:
      on-profile: prod
  flyway:
    locations: classpath:db/migration
  jpa:
    show-sql: false
